@echo off
echo Publicando proyecto...
dotnet publish -c Release -o C:\inetpub\wwwroot\LibreriaFarolito
echo Reiniciando IIS...
iisreset
echo Iniciando ngrok...
ngrok http --url=libreriafarolito.ngrok.pro 80